import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Boxes,
  Building2,
  CalendarClock,
  ChartColumn,
  ClipboardCheck,
  CreditCard,
  Database,
  FileBarChart,
  FileText,
  Gauge,
  HardDrive,
  Hash,
  History,
  Inbox,
  KeyRound,
  LayoutDashboard,
  ListOrdered,
  Map,
  Package,
  PackageCheck,
  PackageOpen,
  PackageSearch,
  PackageX,
  Percent,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  ScanBarcode,
  ScanLine,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Tags,
  Truck,
  UserCheck,
  Users,
  Warehouse,
  Waves,
  Bell,
  Mail,
  Ruler,
  ScrollText,
  Scale,
} from 'lucide-react'

export type NavItem = {
  to: string
  label: string
  icon: LucideIcon
  roles?: string[]
  end?: boolean
}

export type NavSection = {
  id: string
  label: string
  /** When true, section is a single top-level link (first item only). */
  linkOnly?: boolean
  icon?: LucideIcon
  items: NavItem[]
}

const SUPER = ['WMS_SUPERVISOR'] as const

export const NAV_SECTIONS: NavSection[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    linkOnly: true,
    icon: LayoutDashboard,
    items: [{ to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: [...SUPER] }],
  },
  {
    id: 'users',
    label: 'User & Role Management',
    icon: Users,
    items: [
      { to: '/inbound/workers', label: 'Users', icon: Users, roles: [...SUPER] },
      { to: '/users/roles', label: 'Roles', icon: Shield, roles: [...SUPER] },
      { to: '/users/permissions', label: 'Permissions', icon: KeyRound, roles: [...SUPER] },
      { to: '/users/teams', label: 'Teams/Departments', icon: Building2, roles: [...SUPER] },
      { to: '/users/activity-logs', label: 'Activity Logs', icon: Activity, roles: [...SUPER] },
      { to: '/users/login-history', label: 'Login History', icon: History, roles: [...SUPER] },
    ],
  },
  {
    id: 'warehouse',
    label: 'Warehouse Management',
    icon: Warehouse,
    items: [
      { to: '/warehouse/list', label: 'Warehouse List', icon: Warehouse, roles: [...SUPER] },
      { to: '/warehouse/create', label: 'Create Warehouse', icon: Building2, roles: [...SUPER] },
      { to: '/warehouse/zones', label: 'Warehouse Zones', icon: Map, roles: [...SUPER] },
      { to: '/warehouse/aisles', label: 'Aisles', icon: ListOrdered, roles: [...SUPER] },
      { to: '/warehouse/racks', label: 'Racks', icon: Boxes, roles: [...SUPER] },
      { to: '/inventory/utilization', label: 'Storage Capacity', icon: Percent, roles: [...SUPER] },
      { to: '/warehouse/mapping', label: 'Warehouse Mapping', icon: Map, roles: [...SUPER] },
      { to: '/warehouse/status', label: 'Warehouse Status', icon: Gauge, roles: [...SUPER] },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory Management',
    icon: PackageSearch,
    items: [
      { to: '/inventory/dashboard', label: 'Inventory Dashboard', icon: LayoutDashboard, roles: [...SUPER] },
      { to: '/inventory/sku-master', label: 'SKU Master', icon: Tags, roles: [...SUPER] },
      { to: '/inventory/product-master', label: 'Product Master', icon: Package, roles: [...SUPER] },
      { to: '/inventory', label: 'Stock Levels', icon: PackageSearch, roles: [...SUPER], end: true },
      { to: '/inventory/adjustment', label: 'Inventory Adjustment', icon: SlidersHorizontal, roles: [...SUPER] },
      { to: '/warehouse/moves', label: 'Stock Transfer', icon: ArrowLeftRight, roles: [...SUPER] },
      { to: '/inventory/batch-lot', label: 'Batch/Lot Management', icon: Hash, roles: [...SUPER] },
      { to: '/inventory/serial', label: 'Serial Number Management', icon: ScanBarcode, roles: [...SUPER] },
      { to: '/inventory/expiry', label: 'Expiry Management', icon: CalendarClock, roles: [...SUPER] },
      { to: '/inventory/audit', label: 'Inventory Audit', icon: ClipboardCheck, roles: [...SUPER] },
      { to: '/inventory/cycle-count', label: 'Cycle Count', icon: RefreshCw, roles: [...SUPER] },
      { to: '/inventory/damaged', label: 'Damaged Inventory', icon: PackageX, roles: [...SUPER] },
      { to: '/inventory/incoming', label: 'Incoming', icon: Inbox, roles: [...SUPER] },
    ],
  },
  {
    id: 'inbound',
    label: 'Inbound',
    icon: Truck,
    items: [
      { to: '/inbound/dashboard', label: 'Overview', icon: LayoutDashboard, roles: [...SUPER] },
      { to: '/inbound/dock-receive', label: 'Dock Receiving', icon: Truck, roles: ['DOCK_RECEIVER', 'WMS_SUPERVISOR'] },
      { to: '/inbound/unpack', label: 'Unpack', icon: PackageOpen, roles: ['UNPACKER', 'WMS_SUPERVISOR'] },
      { to: '/inbound/assign-putaway', label: 'Assign putaway', icon: UserCheck, roles: [...SUPER] },
      { to: '/inbound/putaway', label: 'Putaway', icon: Package, roles: ['PUTAWAY', 'WMS_SUPERVISOR'] },
    ],
  },
  {
    id: 'outbound',
    label: 'Outbound',
    icon: PackageCheck,
    items: [
      { to: '/outbound/dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: [...SUPER] },
      { to: '/outbound/orders', label: 'Orders', icon: ListOrdered, roles: [...SUPER] },
      { to: '/outbound/allocation', label: 'Allocation', icon: ScanBarcode, roles: [...SUPER] },
      { to: '/outbound/waves', label: 'Send to pick', icon: Waves, roles: [...SUPER] },
      { to: '/outbound/picking', label: 'Picking', icon: PackageCheck, roles: ['PICKER', 'WMS_SUPERVISOR'] },
      { to: '/outbound/exceptions', label: 'Exceptions', icon: AlertTriangle, roles: ['PICKER', 'WMS_SUPERVISOR'] },
      { to: '/outbound/packing', label: 'Packing', icon: PackageOpen, roles: ['PACKER', 'WMS_SUPERVISOR'] },
      { to: '/outbound/labels', label: 'Shipping labels', icon: FileText, roles: ['PACKER', 'WMS_SUPERVISOR'] },
      { to: '/outbound/route-bags', label: 'Route bags', icon: Boxes, roles: ['WMS_SUPERVISOR', 'DOCK_DISPATCHER'] },
      { to: '/outbound/fe-checkin', label: 'FE check-in', icon: ShieldCheck, roles: ['WMS_SUPERVISOR', 'DOCK_DISPATCHER'] },
      { to: '/outbound/assign-fe', label: 'Assign FE', icon: UserCheck, roles: ['WMS_SUPERVISOR', 'DOCK_DISPATCHER'] },
      { to: '/outbound/release-fe', label: 'Release to FE', icon: Truck, roles: ['WMS_SUPERVISOR', 'DOCK_DISPATCHER'] },
      { to: '/outbound/in-field', label: 'In-field', icon: PackageSearch, roles: [...SUPER] },
    ],
  },
  {
    id: 'returns',
    label: 'Returns & RTO',
    icon: RefreshCw,
    items: [
      { to: '/returns/orders', label: 'Return Orders', icon: ShoppingCart, roles: [...SUPER] },
      { to: '/returns/inspection', label: 'Return Inspection', icon: ClipboardCheck, roles: [...SUPER] },
      { to: '/returns/qc', label: 'Quality Check', icon: ShieldCheck, roles: [...SUPER] },
      { to: '/returns/restock', label: 'Restock Inventory', icon: Archive, roles: [...SUPER] },
      { to: '/returns/damage', label: 'Damage Management', icon: PackageX, roles: [...SUPER] },
      { to: '/returns/rto', label: 'RTO Processing', icon: Truck, roles: [...SUPER] },
      { to: '/returns/refunds', label: 'Refund Status', icon: Banknote, roles: [...SUPER] },
      { to: '/returns/reports', label: 'Return Reports', icon: FileBarChart, roles: [...SUPER] },
    ],
  },
  {
    id: 'exceptions',
    label: 'Exception Center',
    icon: AlertTriangle,
    items: [
      { to: '/exceptions/inventory-mismatch', label: 'Inventory Mismatch', icon: Scale, roles: [...SUPER] },
      { to: '/exceptions/damaged-sku', label: 'Damaged SKU', icon: PackageX, roles: [...SUPER] },
      { to: '/exceptions/wrong-scan', label: 'Wrong Scan', icon: ScanLine, roles: [...SUPER] },
      { to: '/exceptions/courier-rejection', label: 'Courier Rejection', icon: Truck, roles: [...SUPER] },
      { to: '/exceptions/failed-dispatch', label: 'Failed Dispatch', icon: AlertTriangle, roles: [...SUPER] },
      { to: '/exceptions/comments', label: 'Comments', icon: ScrollText, roles: [...SUPER] },
      { to: '/exceptions/attachments', label: 'Attachments', icon: FileText, roles: [...SUPER] },
      { to: '/exceptions/resolution', label: 'Resolution Workflow', icon: ClipboardCheck, roles: [...SUPER] },
    ],
  },
  {
    id: 'barcodes',
    label: 'Barcode & QR Management',
    icon: QrCode,
    items: [
      { to: '/barcodes/generator', label: 'Barcode Generator', icon: ScanBarcode, roles: [...SUPER] },
      { to: '/barcodes/qr-generator', label: 'QR Code Generator', icon: QrCode, roles: [...SUPER] },
      { to: '/barcodes/printing', label: 'Barcode Printing', icon: Printer, roles: [...SUPER] },
      { to: '/barcodes/templates', label: 'Label Templates', icon: Tags, roles: [...SUPER] },
      { to: '/barcodes/scan-history', label: 'Scan History', icon: History, roles: [...SUPER] },
      { to: '/barcodes/scanner-settings', label: 'Scanner Settings', icon: Settings, roles: [...SUPER] },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: CreditCard,
    items: [
      { to: '/finance/customer-billing', label: 'Customer Billing', icon: Receipt, roles: [...SUPER] },
      { to: '/finance/vendor-billing', label: 'Vendor Billing', icon: Banknote, roles: [...SUPER] },
      { to: '/finance/warehouse-charges', label: 'Warehouse Charges', icon: Warehouse, roles: [...SUPER] },
      { to: '/finance/storage-charges', label: 'Storage Charges', icon: Archive, roles: [...SUPER] },
      { to: '/finance/pick-pack-charges', label: 'Picking & Packing Charges', icon: PackageCheck, roles: [...SUPER] },
      { to: '/finance/invoices', label: 'Invoice Management', icon: FileText, roles: [...SUPER] },
      { to: '/finance/payments', label: 'Payment Tracking', icon: CreditCard, roles: [...SUPER] },
      { to: '/finance/credit-notes', label: 'Credit Notes', icon: ScrollText, roles: [...SUPER] },
      { to: '/finance/reports', label: 'Reports', icon: FileBarChart, roles: [...SUPER] },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    icon: BarChart3,
    items: [
      { to: '/reports/inventory', label: 'Inventory Reports', icon: PackageSearch, roles: [...SUPER] },
      { to: '/reports/inbound', label: 'Inbound Reports', icon: Truck, roles: [...SUPER] },
      { to: '/reports/outbound', label: 'Outbound Reports', icon: PackageCheck, roles: [...SUPER] },
      { to: '/reports/orders', label: 'Order Reports', icon: ListOrdered, roles: [...SUPER] },
      { to: '/reports/warehouse-performance', label: 'Warehouse Performance', icon: Gauge, roles: [...SUPER] },
      { to: '/reports/user-activity', label: 'User Activity', icon: Activity, roles: [...SUPER] },
      { to: '/reports/financial', label: 'Financial Reports', icon: Banknote, roles: [...SUPER] },
      { to: '/reports/kpi', label: 'KPI Dashboard', icon: ChartColumn, roles: [...SUPER] },
      { to: '/reports/export', label: 'Export Reports', icon: FileBarChart, roles: [...SUPER] },
      { to: '/reports/sla', label: 'SLA Dashboards', icon: CalendarClock, roles: [...SUPER] },
      { to: '/reports/ageing', label: 'Ageing', icon: History, roles: [...SUPER] },
      { to: '/reports/dead-stock', label: 'Dead Stock', icon: PackageX, roles: [...SUPER] },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    items: [
      { to: '/settings/company-profile', label: 'Company Profile', icon: Building2, roles: [...SUPER] },
      { to: '/settings/warehouse', label: 'Warehouse Settings', icon: Warehouse, roles: [...SUPER] },
      { to: '/settings/notifications', label: 'Notification Settings', icon: Bell, roles: [...SUPER] },
      { to: '/settings/email-sms', label: 'Email & SMS Templates', icon: Mail, roles: [...SUPER] },
      { to: '/settings/courier', label: 'Courier Integrations', icon: Truck, roles: [...SUPER] },
      { to: '/settings/api', label: 'API Settings', icon: KeyRound, roles: [...SUPER] },
      { to: '/settings/tax', label: 'Tax Settings', icon: Receipt, roles: [...SUPER] },
      { to: '/settings/uom', label: 'Units of Measurement', icon: Ruler, roles: [...SUPER] },
      { to: '/settings/master-data', label: 'Master Data', icon: Database, roles: [...SUPER] },
      { to: '/settings/backup', label: 'Backup & Restore', icon: HardDrive, roles: [...SUPER] },
      { to: '/settings/system-logs', label: 'System Logs', icon: ScrollText, roles: [...SUPER] },
    ],
  },
]
